server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    session:
      timeout: 120s

eureka:
  instance:
    health-check-url-path: "/actuator/health"
  client:
    serviceUrl:
      defaultZone: "http://localhost:9102/eureka"

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
    ConnectTimeout: 10000
    ReadTimeout: 10000
    
info:
  app:
    version: 1.0-Beta
