spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    sql-script-encoding: UTF-8
    
#commande:
#  ribbon:
#    listOfServers: "localhost:9002", "localhost:9012"