#server:
# port: ${PORT:9000}

spring:
 security:
   user:
     name: "admin"
     password: "admin"
     
zuul:
  host:
    socket-timeout-millis: 50000
    connect-timeout-millis: 50000
